### ISSUE TITLE
Add export / import feature to check older sessions

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/retro#113]
**Is your feature request related to a problem? Please describe.**

Currently the boards are outdated at some point. That's totally fine but checking progress from time to time if specific points have been addressed or not would be nice. To do so, an export and import feature would be great.

**Describe the solution you'd like**

Add an export / import feature that contains all board information and allows to reset the board to the specific session.

**Comment by yduman** [comment]
Thanks for this feature request! To get your point correct:

- We currently have export/import for boards as PNGs
- We currently also have export/import for board data, but this is rather using a board as a template, so we just keep the columns but every item is deleted

Your suggestions would also export/import board data, but this time you want to continue the work on the imported board. Did I get you right? If that's the case, I can realize this as the first feature for the next release, since most of the logic is already present.

**Comment by NearW** [comment]
As a **Retro Board user**, I want to persist my work and continue working with the same data in a new session, so that I don't have to create all cards and columns again by hand.

**Acceptance Criteria**
- Exported JSON file is extended so that it contains all existing cards
- Importing a JSON file restores all cards from the file
- Importing a JSON file should propagate the new state to all participants
- Importing a JSON file should overwrite the current state
- Votes should not be exported
- File version is incremented accordingly (1.1.0)
- Old file versions can still be imported (1.0.0)

**Out of scope**
- Merging existing board with imported file is not implemented
- No checksum for imported/exported files

**Comment by NearW** [comment]
Already implemented.
